project:
  type: book
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: 
      - litera
      - theme.scss
    toc: true
    html-math-method: katex
    callout-icon: false
    callout-appearance: simple
    page-layout: full
    grid:
      sidebar-width: 300px
      body-width: 1200px
    number-depth: 2

book:
  title: "Joeyonng's Notebook"
  author: "Litao Qiao"

  chapters:
    - "index.md"
    - "notations.md"
    - part: "Linear Algebra"
      chapters:
        - "Linear Algebra/01_Fields.md"
        - "Linear Algebra/02_Spaces.md"
        - "Linear Algebra/03_Vectors_and_Matrices.md"
        - "Linear Algebra/04_Span.md"
        - "Linear Algebra/05_Linear_Independence.md"
        - "Linear Algebra/06_Basis.md"
        - "Linear Algebra/07_Dimension.md"
        - "Linear Algebra/08_Linear_Map.md"
        - "Linear Algebra/09_Rank.md"
        - "Linear Algebra/10_Inner_Product.md"
        - "Linear Algebra/11_Norm.md"
        - "Linear Algebra/12_Orthogonality.md"
        - "Linear Algebra/13_Unitary_Matrix.md"
        - "Linear Algebra/14_Complementary_Subspaces.md"
        - "Linear Algebra/15_Projection.md"
        - "Linear Algebra/16_Orthogonal_Complement.md"
        - "Linear Algebra/17_Orthogonal_Decomposition.md"
        - "Linear Algebra/18_Singular_Value_Decomposition.md"
        - "Linear Algebra/19_Pseudoinverse.md"
        - "Linear Algebra/20_Orthogonal_Projection.md"
        - "Linear Algebra/21_Affine_Projection.md"
        - "Linear Algebra/22_Determinants.md"
        - "Linear Algebra/23_Eigensystems.md"
        - "Linear Algebra/24_Similarity.md"
        - "Linear Algebra/25_Diagonalization.md"
        - "Linear Algebra/26_Normal_Matrices.md"
        - "Linear Algebra/27_Positive_Definite_Matrices.md"
    - part: "Probability and Statistics"
      chapters:
        - "Probability and Statistics/01_Probability.md"
        - "Probability and Statistics/02_Random_Variables.md"
        - "Probability and Statistics/03_Expectation.md"
        - "Probability and Statistics/04_Common_Distributions.md"
        - "Probability and Statistics/05_Moment_Generating_Functions.md"
        - "Probability and Statistics/06_Concentration_Inequalities_I.md"
        - "Probability and Statistics/07_Convergence.md"
        - "Probability and Statistics/08_Limit_Theorems.md"
        - "Probability and Statistics/09_Maximum_Likelihood_Estimation.md"
        - "Probability and Statistics/10_Bayesian_Estimation.md"
        - "Probability and Statistics/11_Expectation_Maximization.md"
        - "Probability and Statistics/12_Concentration_Inequalities2.md"
    - part: "Learning Theory"
      chapters:
        - "Learning Theory/1_Statistical_Learning.md"
        - "Learning Theory/2_Bayesian_Classifier.md"
        - "Learning Theory/3_Effective_Class_Size.md"
        - "Learning Theory/4_Empirical_Risk_Minimization.md"
        - "Learning Theory/5_Uniform_Convergence.md"
        - "Learning Theory/6_PAC_Learning.md"
        - "Learning Theory/7_Rademacher_Complexity.md"

  search: 
    location: sidebar
    type: textbox

  navbar:
    title: "Joeyonng"
    pinned: true
    logo-href: "https://joeyonng.github.io/joeyonng/"
    left:
      - href: "index.md"
        text: "Notebook"
      - href: "https://joeyonng.github.io/joeyonng/Notes/" 
        text: "Drafts"
      - href: "https://joeyonng.github.io/joeyonng/"
        text: "About"

    right:
      - href: "https://joeyonng.github.io/joeyonng-backyard/"
        text: "Backyard"
  
  sidebar:
    collapse-level: 1